spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo

server:
  port: 8082

spring:
  application:
    name: Item-Delivery-BPM
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
